server.port=8081
spring.application.name=internverse-backend
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/internverse}

app.jwt.secret=${JWT_SECRET_BASE64:U3VwZXJTZWNyZXRLZXlGb3JJbnRlcm52ZXJzZUFwcDEyMzQ1Njc4OTA=}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}